config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :users
  resources :sessions
  resources :blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true, length: { minimum: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  attr_accessor :password, :password_confirmation

  validates_presence_of :email, message: "邮箱不能为空"
  validates :email, uniqueness: true
  validates_presence_of :password, message: "密码不能为空",
    if: :need_validate_password
  validates_presence_of :password_confirmation, message: "密码确认不能为空",
    if: :need_validate_password
  validates_confirmation_of :password, message: "密码不一致",
    if: :need_validate_password
  validates_length_of :password, message: "密码最短6位",
    minimum: 6,
    if: :need_validate_password

  private
  def need_validate_password
    self.new_record? ||
      (!self.password.nil? or !self.password_confirmation.nil?)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      redirect_to @blog
    else
      render 'new'
    end
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blog_url
    else
      render 'edit'
    end
  end

  def destroy
    @blog = Blog.find(params[:id])
    @blog.destroy

    redirect_to blogs_path
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :text)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :auth_user, except: [:destroy]

  def new
  end

  def create
    #login是sorcery的登录方法
    if user = login(params[:email], params[:password])
      flash[:notice] = '登陆成功'
      redirect_to root_path
    else
      flash[:notice] = "邮箱或者密码错误"
      redirect_to new_session_path
    end
  end

  def destroy
    #logout是sorcery的退出方法
    logout
    flash[:notice] = "退出登陆"
    redirect_to root_path
  end

  private

  def auth_user
    #logged_in?是sorcery的判断登录方法
    if logged_in?
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  #用户注册
  def create
    @user = User.new(params.require(:user)
      .permit(:email, :password, :password_confirmation))

    if @user.save
      flash[:notice] = '注册成功，请登录'
      redirect_to new_session_path
    else
      render action: :new
    end
  end

  #用户密码修改
  def change_password
    if current_user.valid_password?(params[:old_password])
      current_user.password_confirmation = params[:password_confirmation]

      if current_user.change_password!(params[:password])
        render json: {status: 'ok', msg: '密码修改成功'}
      else
        render json: {status: 'error', msg: current_user.errors.messages.values.flatten}
      end
    else
      render json: {status: 'error', msg: '旧密码不正确'}
    end
  end

  #用户发送忘记密码邮件,这里需要对邮件进行配置
  def send_forget_password_email
    @user = User.find_by(email: params[:email])
    if @user
      @user.deliver_reset_password_instructions!
      render json: {status: 'ok', msg: "重置密码的链接已发送到上面的邮箱"}
    else
      render json: {status: 'error', msg: '指定邮箱不存在'}
    end
  end

  #密码重置
  def reset_password
    @user = User.load_from_reset_password_token(params[:token])
    if @user
      @user.password_confirmation = params[:password_confirmation]
      if @user.change_password!(params[:password])
        render json: {status: 'ok', msg: '密码修改成功'}
      else
        render json: {status: 'error', msg: @user.errors.messages.values.flatten}
      end
    else
      render json: {status: 'error', msg: 'token不正确或者已过期'}
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogs/edit.html.erb
<h1>修改博客</h1>
<%= form_for @blog do |f| %>
  <p>
    <%= f.label "标题" %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label "内容" %>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit "提交" %>
  </p>
<% end %>
</br>
<%= link_to '返回', blogs_path %>

app/views/blogs/index.html.erb
<h1>个人博客首页</h1>
<p>
  <%= link_to '新建博客', new_blog_path %>
</p>

<table class="table table-bordered table-hover">
  <tr class="text-info">
    <th>标题</th>
    <th>内容</th>
    <th>操作</th>
  </tr>
  <% @blogs.each do |blog| %>
  <tr class="text-info">
    <td><%= link_to "#{blog.title}", blog_path(blog)  %></td>
    <td><%= blog.text %></td>
    <td><%= link_to "显示", blog_path(blog) %><span style="margin-left: 5px">|</span>
        <%= link_to "修改", edit_blog_path(blog) %><span style="margin-left: 5px">|</span>
        <%= link_to "删除", blog_path(blog),
            method: :delete, data: {confirm: "确认删除 ？"} %>
    </td>
  </tr>
  <% end %>

</table>

app/views/blogs/new.html.erb
<h1>新建博客</h1>
<%= form_for @blog do |f| %>
  <% if @blog.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@blog.errors.count, "error") %>禁止
      新建博客出现错误
    </h2>
    <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label "标题" %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label "内容" %>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit "提交" %>
  </p>
<% end %>
</p>
<%= link_to '返回', blogs_path %>

app/views/blogs/show.html.erb
<h1>Show</h1>
<p>
  <strong>标题:</strong>
  <%= @blog.title %>
</p>
<p>
  <strong>内容:</strong>
  <%= @blog.text %>
</p>
<%= link_to '返回', blogs_path %>
</p>
<%= link_to '修改', edit_blog_path %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">猎人博客
        <br>程序员的专属博客

    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">猎人博客</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <% if !current_user %>
                  <li><%= link_to("注册", new_user_path) %> </li>
                  <li><%= link_to("登入", new_session_path) %></li>
                <% else %>
                  <a><%= link_to("登出", session_path(session),
                        method: :delete, data: { confirm: '确认退出吗?' } ) %>
                  </a>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HunterBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render 'common/navbar' %>
      <%= yield %>
    </div>
    <%= render 'common/footer' %>
  </body>
</html>

app/views/users/new.html.erb
<h1>用户注册</h1>
<div>
  <% unless @user.errors.empty? %>
    <ul>
      <% @user.errors.messages.values.flatten.each do |error| %>
        <li><%= error %></li>
      <% end -%>
    </ul>
  <% end -%>
</div>
<%= form_for :user, url: users_path, method: :post, html: { class: 'form-horizontal', id: "user_form"} do |f| %>
  <div class="form-group">
    <div class="col-lg-12">邮箱 *</div>
    <div class="col-lg-12">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-12">密码 *</div>
    <div class="col-lg-12">
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-12">密码确认 *</div>
    <div class="col-lg-12">
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-12">
      <input type="submit" name="create_user_submit" value="创建账户" class="col-xs-12 btn btn-primary">
    </div>
  </div>
<% end %>

app/views/welcome/index.html.erb
<h1>猎人博客</h1>
<%= link_to '返回', blogs_path %>